hash-format = "sha256"

[[files]]
file = "config/stackdeobf.json"
hash = "0bf1c15a12a466be1dcee4bc2bc751a464cecde6dd5402e959856513a1d83ad7"

[[files]]
file = "mods/accessories.pw.toml"
hash = "97befad2275e44c557794fbd321b154510279ce7906426607288062e096df86d"
metafile = true

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "26085aa8480f728633c0b84a5eb1879f2911993905c425f3596fb2bef0ed94cc"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "3fab60aca0fee9153c49b40e1b06b1deebb23800dce7b8b8f471e23f43f3efe5"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "2e73c47d8922a54319a54b1edfdf57c0b5b7dec88b67089eca704cdae21a0395"
metafile = true

[[files]]
file = "mods/animal_feeding_trough.pw.toml"
hash = "36b311ab2c828ad8c490b539ae0cffdac8438be7c997a71a1c782af924114c15"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "bc5bb9c17c071be6f2abb8f678a1f4f82252971070c8f9b2249169558999dc64"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/artsandcrafts.pw.toml"
hash = "1d1af91a94e0b73686f7d2556659a6e6e4316a3d37315d0d227e0dea661e6720"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "5601649308a7d9f1658a942bbd48d3bd899a81fabd4ea1296952b48474d1ee1d"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "dc3575dab2673b765947da8a87c01464ea77af8fe355fe18579dce514b35be7a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "a9f6cf1a98bc318c887b672aecaff6ffdbf33a6ec06af5f2686b292988d0846e"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "8bc168948c5f92a10252f12ad4f41caeefbe508f0326fc4185217d60c4cb2292"
metafile = true

[[files]]
file = "mods/chimes.pw.toml"
hash = "5d343f1b9dd2da58dd4828fcccce26c18e5cd36bc3e52b6e1e9ce8b8eb17b966"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "a4d21da45c40e8f1e3b76c9855ea3f1c15736cf2b12475e9de3efd05f8f48a8d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/cobbledgacha.pw.toml"
hash = "0bd4f168484182b6898b4e4ee06aeb4ac2eadf03f3b9749653d4e3203f5a0a66"
metafile = true

[[files]]
file = "mods/cobblefurnies.pw.toml"
hash = "e4017e270ceacfe8dff8cdba6a657b903c002133a3bc88e8dbd54c6f55812b16"
metafile = true

[[files]]
file = "mods/cobblemon-delight.pw.toml"
hash = "af35f4a6055648b3222f627ee383f7322d99efeca9afd0143021da0bfabb7edd"
metafile = true

[[files]]
file = "mods/cobblemon-integrations.pw.toml"
hash = "d627d0fb3f5c037ccc75d6504749bc9beed6b73068f740f79ece59fa4748508e"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "9e26417f1c9612886d58cd8ede0e618a5adb6b85fc52d2f2ee38d289e2fd7a5b"
metafile = true

[[files]]
file = "mods/cobblemon-move-inspector.pw.toml"
hash = "784184013f308a4fbec92b2ab5610969ca33ec547fd953fcc9d50cd2095d63e2"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "d0d21c8cd26fc4ddcdd03893e4b7ad5e1d1a4701a272f002f2932f9686770a6e"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "55176d940577a671525a837cb9db04380a0d3339f2b93314d5df9001653347f9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4f97764f3cb4c74f84afbe32cf8a1d2cefecda129c0f1441906562dcb8f2b8cb"
metafile = true

[[files]]
file = "mods/convenient-decor.pw.toml"
hash = "12dd618f9358f0dd7f770e3bdbeb93b1dc9d7dde58aae6e197511015dce6e1dd"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "41440aa391c6fb6ba275a47a78c4353fb5a2e4a76b2cd8d91e7751c7507a2637"
metafile = true

[[files]]
file = "mods/dehydration.pw.toml"
hash = "e65d2ba782b365d99ff23693800f47334e7cd5a3bba2cd63763bb07715781089"
metafile = true

[[files]]
file = "mods/display-delight-fabric.pw.toml"
hash = "f6607a5e138070adf524122e46679df89e8146450a876d6c8a18eb13854c85be"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-ancient-city-overhaul.pw.toml"
hash = "e811185f1b2c3d26c5bb3dfcab59d1e86dee35815f7f25a10efec48cf4f48b4e"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-desert-temple-overhaul.pw.toml"
hash = "4f5fa8f414a522e519113b9c938abb7fe5d827f8c1f039fc77649f1c0623c94e"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-end-castle-standalone.pw.toml"
hash = "1425d8630354828c3df9e8a4c2283e257601b94c82503175535dcd9ec750ddc4"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-jungle-temple-overhaul.pw.toml"
hash = "994a188c1acaae5d441895f388396b50fedaab6e0a18c1c0fe131a31c32a6132"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-nether-fortress-overhaul.pw.toml"
hash = "e2c2c45de206f7c2c9a0c839a85eb8900cccc8a7dc3b328fb4711646f669ae7c"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-ocean-monument-overhaul.pw.toml"
hash = "a4c25ad00c2e6ad87500640edee15330dfd22a522b5f8a4066b83aa552ef3045"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-pillager-outpost-overhaul.pw.toml"
hash = "bee4f2f4f7abd7c1f14f3f4690ed5e26f18cb732b962f2f5b4b6c0cd522662b9"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-stronghold-overhaul.pw.toml"
hash = "54d67580e5ce1338e9813fe571338fcb7503989801db66fd901a997f4220bc29"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-swamp-hut-overhaul.pw.toml"
hash = "834584cac85ff31f7e76527389f7fbe3358eb1fd5ae8ed2c9146032bda8b8717"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-woodland-mansion-overhaul.pw.toml"
hash = "8a6277690b31e2e183a1a01c30c0517b226e25203d88a62fe1d9618d993e4155"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "447ec530620e3c0da62316cb3358e43c15132084aab22ba992fefac199ca92a9"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7c9d9ae612abbb7593b3d5b8306442b87c381fa38efbef2fcbf17e8669552cdc"
metafile = true

[[files]]
file = "mods/enderscape.pw.toml"
hash = "40be4ad7e0404bff407c28d93f9d5ae70cbf5c610c0e7693650640a3ae8354fa"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
hash = "389c30cfae2e35405bc8efe5c5e1eb853ab8b3e031d45e889b597c581632d420"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "dde1c3036a0cc2c280e2254a5ffd647fbae47dd72c77dd564f35d791d6d21709"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "1fbcec6fae4237b80bf2becfc06fb52a49512821f402b5928b1e2533c73b3142"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "2ada3ac958fb2beff2e913d3094a06cab1b6a794de0e4132b014437d409af397"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "6b0b4bf6142ff8a72758914307684881bd7b545884bb8049f8cf6442670ec8a3"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
hash = "a4430406a1174342e78d863ea1d00223f574a51364989364891b8d0430cc25b4"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "2b5f19e8d0dde0e603b4df323970429589147eef5d3658ce9f63d4a4d2ace93c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "debc633d962665af2873b7e4c74a5bd8da18d6a883971e73b9039f9612f457b7"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "7b65b2c82aabb6fe1b97b1f6aa29f870c5dfcbee514ae8a2e5520164ce9f8861"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "53c50190307a3b206fc1a363197d713bc98f5bb8bc391f7f9827132e629643d3"
metafile = true

[[files]]
file = "mods/gliders.pw.toml"
hash = "00c297ac149ba938cd102ce2ec50939b9bf8c64c68fe6f3b7bc9f1f168d489de"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "8cb1da4da5375889e24a5e99882fd6f48121e0eb9f028227c84e4375aaf76381"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "37e14a7a0b033feafd7fc1cb82842c128b1b2f2053dd1d11206834d7fcc6f597"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "ab5b5ecade1d9cf981d11fee68d5f42e5d933a4e4d9b15b2657d8da2a4f8304a"
metafile = true

[[files]]
file = "mods/immersive-melodies.pw.toml"
hash = "0a5b03c7ebac217b8f5dc6314039a7338fd786b63146621996632acd9d8dbc8e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jinxedlib.pw.toml"
hash = "2aa483960df75b01d3a1e08fcce318e53da714d26b0109463721f8eb6c7e062b"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "502d4ba2ca8c7f6f52830cfc43fc12b567023266f2b557ee2b8eea737b58f8ea"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "788b10db97a8c2e1fdca7a4450fd0aac96c9e6b7fe29fccc13bcf4487964e16d"
metafile = true

[[files]]
file = "mods/macu-lib.pw.toml"
hash = "8ec15be36b7e258a60ddefe8c0af23b9262e5503d62fb1a16b45a78e13118005"
metafile = true

[[files]]
file = "mods/mighty-mail.pw.toml"
hash = "be23f8e39be6368729dc085d3443c8739092ad42df2740dca396b3914733c74c"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "c816127b8e0dc651799a8068ea69f0f27434741701b02f86e4ab72277c54230c"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "230b1f5cd118accacf41f268e122bd420420d9e5248d43513090804739a832f3"
metafile = true

[[files]]
file = "mods/niftycarts.pw.toml"
hash = "421431bdba887c114dffd4be28fcdc0e6dddbfeadc518f5d02d55b8f3d575ece"
metafile = true

[[files]]
file = "mods/nightlights.pw.toml"
hash = "6b63d15284f95807dd5dcf19e6c1d0132cbac508426162d8db775a1c3a6a228d"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "acc5199aefdbb418065cf4f3554693fcf9797dc1851a36ca7bad9e660b127763"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "39be6d2deb24772f6c0a84a5b267e2dd676c320ba6b0a73e8b143a11de73a321"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/particular.pw.toml"
hash = "9bceeadea46405d869a5b781efb109ac9fd7b4455c9c536092ccc93a135bad96"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "f89967ea9150d6e5371057dc31fc8b8180c79808410ee6318088fcf78a16f58f"
metafile = true

[[files]]
file = "mods/plushie-buddies.pw.toml"
hash = "c089071bf05337828e521ff008b962451e73d3eeb886b6adee4d57e177318784"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "9d68782624dadddacfd248604944572d450e4b90dcec55329829717b837af1db"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "f013040d2544856ca9f8fe4e07e040aa8a78c87ace3426743a8429d73cba81a3"
metafile = true

[[files]]
file = "mods/reframed.pw.toml"
hash = "b6021cd52db0eee9a48d1aa31552d1158bf8b454b424ea0ddda9011e324efa0b"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d3f633dd12cd039a4e58dd398d1c80a324b0d78b9da5b3972b69640bfed211ed"
metafile = true

[[files]]
file = "mods/river-redux.pw.toml"
hash = "3704ac7c16a5c66d5d8b882540b8cdaf62062666f83be204dbe2157e229ac0b5"
metafile = true

[[files]]
file = "mods/satin-free-wakes.pw.toml"
hash = "da82584dc5c26adafb4df9b69fa2ed710ead914ce8384058665fcfa85950f5fa"
metafile = true

[[files]]
file = "mods/shutters.pw.toml"
hash = "2f55883a243000c4cc40adcee35c2c4e1508f33267679a35ef4736bb238132c1"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cc98ef15cb0fb331703af145ea92255765247a2b1d27b87d05a44ad0dc6d9b4e"
metafile = true

[[files]]
file = "mods/sitting+.pw.toml"
hash = "6849cbe791205308a6cb7e6d06172dca663446f7c6573ee2ce10f537aef9f16a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sooty-chimneys.pw.toml"
hash = "081062cb61b5528765c12c29802e80b4ea656d58302a1f2ae19117ac2dc6eebf"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "a4eebb2bda9daccc5444b8bd2d91f4ee8ce2325dd51436cb785ca33530b98ecd"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "693fdc79c18086a2a939b45de97ca918d895d5a4247d2a0bba94bf53661bc705"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "4ea85fa7d750bf5a167fe9652f2ac896d12ab068dacb8b04539e316ba5b74042"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "1d0e54184bf7982547240482dd90ae24a34eea89927ca3b3f23b37e7b2c17574"
metafile = true

[[files]]
file = "mods/spuds-shops.pw.toml"
hash = "71a11eab06d7694ac2c6afe680036c694d98289f4ea6adb4c44a0112fd0ac8f4"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "b97b297fab12e137c58874ae776402cfa29374c8ff50c9f18ef27442b65336e6"
metafile = true

[[files]]
file = "mods/stone-zone.pw.toml"
hash = "9d3836011f034c50a1a20cab49dedd60d881ecf7af1af6f46296c192989a65d6"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "afce539f4b5192c6f1cc65de89964babe5167c22c0387f5bb5a1d4227671b754"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "ecfccbecbcd49d3cf878f4df49adc526c4185cc8d8d5c32e292dd43f95a17ab9"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "3bce642dc87eae74f767fdcd779374c3bc76b2f74d8f2fadb8f9daf813e69aa2"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "39426bfeeab22ea17f94fd3904dd9b78f9a3c9b4ddcb732b734ddbfd0e3568af"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "388ad48f4bd97f7391bfcedd485fe5faa2c6ecffd3369dd7d3cbf031b7b04551"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "d9b210470eeaca6109002dcc8c1442dbbef5468bbf7be516651e7fc25b3d5c5e"
metafile = true

[[files]]
file = "mods/woodlandsthe-core.pw.toml"
hash = "1d87b5a76ba977c13d678f6cdc8598bfd71a26df747c05eecafb452a7310b464"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "120b1b5e775ec88fb6b6a3c11f4d3685a2b28d0badfb73b3606f946599d6b587"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "80d14aa6af38caa8f61f2bd1e98744f6aeda9c0701684ed80422ded03ebab640"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "af20070dd9497817a83162c17b181a0a44f7213ea302d059a81c5aed02d0c877"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
hash = "5be05538347e59b65357ecb31c28c90edd3769309fa864222d7116ccd7e8a446"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "4d98bdba90cdeae788a747bb6fe7d438ba49fdc4eb67c38d4573304eec4a2ef8"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "a9f7ce3ef90cd500e451ff6534d42f0532150d5f207c974468295fbe8c7b5a47"
metafile = true

[[files]]
file = "servers.dat"
hash = "d411cc33e7fd7fc52338b3563435c42817a4ca2fcf580452a028ff5594b520d0"
