name = "Petal SMP Modpack"
author = "macuguita"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "132c03e6bb2dfb5d187224dd6fbb7718ca1447a9aad277b530c1bceaa4c34846"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
