name = "Daisy SMP Modpack"
author = "macuguita"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44e9f7866cbcfac814271f960ceba7f4eec890a11240df50e99d23bb6ce8ca95"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
