name = "Daisy SMP Modpack"
author = "macuguita"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06655b32aa14d1dadf6abd9d327b208ad2d236857f095b1eb41983fa7302a660"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
