name = "Daisy SMP Modpack"
author = "macuguita"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a3279de16e3f2317a09a8b80809aef47b5c657b2d3b9cf84f7358e168e1774"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
