name = "Daisy SMP Modpack"
author = "macuguita"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4ecad593422bd06ceb0596f40937ad291067f0e06365ad47db7d3036423c5dd"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
