name = "Daisy SMP Modpack"
author = "macuguita"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c364b59a60a5efca4f6d0820b4b977f96f79397ee409f926ecda2d5350b0a3ba"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
